apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-argo
spec:
  project: default
  source:
    repoURL: https://github.com/Gaurav098766/argocd-deploy.git
    path: infra/k8s
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
